name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world:
    name: Hello world job
    runs-on: ubuntu-20.04
    steps:
      - name: Print hello world
        run: |
          echo Hello World!
      - name: Current datetime
        run: |
          date -u
      - name: Show folder contents
        run: |
          ls -l